# Generated by Django 5.1.4 on 2024-12-26 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_date', models.DateField(help_text='Enter the event date.')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deadline', models.DateField(default=datetime.date.today, verbose_name='Submission Deadline')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField(help_text='Shift start time.')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Shift End Time')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('last_updated', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userproflile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='enter a unquie username', max_length=30, null=True, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('bio', models.CharField(blank=True, help_text='write a short bio about yourself', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('qualification', models.CharField(choices=[('1', 'b.etch'), ('2', 'm.tch'), ('3', 'bcom')], db_index=True, max_length=100, null=True, verbose_name='quali')),
                ('remark', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
